### ISSUE TITLE
/darwin_arm64/compile: signal: killed

### ISSUE THREAD

**Issue by chenxibob** [guanguans/id-validator#15]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/9959074/155259776-85b893ea-e10f-4689-8134-ae46b102ae5f.png">

调试代码的时候报错，16G内存都不够

**Comment by Umenezumi** [comment]
请问这个问题不解决吗？

**Comment by guanguans** [comment]
更新到最新版本再尝试。
