### ISSUE TITLE
您好，请问严格模式与非严格具体什么区别？另外地址区划代码与年份不同的错误身份证能否校验出来？

### ISSUE THREAD

**Issue by ZhuningS** [guanguans/id-validator#19]
// 验证身份证号合法性严格模式与非严格具体什么区别？
	ffmt.P(idvalidator.IsValid("440308199901101512", false)) // 非严格模式验证大陆居民身份证18位
	ffmt.P(idvalidator.IsValid("440308199901101512", true))  // 严格模式验证大陆居民身份证18位

关于校验地址码有效期功能：
例如假身份证号370620199505100123，但是1995年威海地区压根没有370620的地址区划代码。（前六位地址码错误，370620地址码在1987年就废弃了）

**Comment by guanguans** [comment]
@ZhuningS 非严格模式下，则不会检查【地址码正式启用的年份】与【身份证上的出生年份】的关系([相关代码](https://github.com/guanguans/id-validator/blob/main/helper.go#L85-L90))。
