### ISSUE TITLE
dlv模式下内存问题

### ISSUE THREAD

**Issue by ruziyi** [guanguans/id-validator#2]
dlv模式下会导致compile进程内存飙升

**Comment by aimingo** [comment]
确实存在这个问题。

**Comment by 39Er** [comment]
+1 
go build -v -gcflags all=-N

**Comment by pylist** [comment]
div模式是啥, 我使用身份证校验有影响么

**Comment by jinquan1248** [comment]
> div模式是啥, 我使用身份证校验有影响么

那是dlv，猜测是一种调试模式，我也在debug模式下遇到这个问题了🤷‍♂️。

**Comment by cuitking** [comment]
怎么优化呢
