### ISSUE TITLE
goland下不能进行debug模式

### ISSUE THREAD

**Issue by pylist** [guanguans/id-validator#20]
**Describe the bug**
goland调试模式下报错

**To Reproduce**
goland下进行debug

**Expected behavior**
能够正常调试程序

**Screenshots**
![image](https://user-images.githubusercontent.com/52667561/157247198-2d839795-c51d-4ab7-8120-f4e1de7b0a26.png)

**Additional context**
无

**Comment by Umenezumi** [comment]
这个问题不解决了吗

**Comment by guanguans** [comment]
> 这个问题不解决了吗

抱歉目前没找到解决办法，如果你这边能够修复可以提 `pr` 过来。

**Comment by Umenezumi** [comment]
> > 这个问题不解决了吗
> 
> 抱歉目前没找到解决办法，如果你这边能够修复可以提 `pr` 过来。

好的，我研究下，看看有没有能力解决这个问题

**Comment by zzhaoh** [comment]
> > > 这个问题不解决了吗
> > 
> > 
> > 抱歉目前没找到解决办法，如果你这边能够修复可以提 `pr` 过来。
> 
> 好的，我研究下，看看有没有能力解决这个问题

可以把data包里的全局变量放在方法里返回吗，addressCodeTimeline这个map太大了。
