### ISSUE TITLE
230119开头号段不通过验证

### ISSUE THREAD

**Issue by kingzyt** [guanguans/id-validator#34]

**Comment by kingzyt** [comment]
原因同https://github.com/guanguans/id-validator/issues/33

**Comment by kingzyt** [comment]
建议在GetInfo或是IsValid中添加一个忽略校验第5~6位，或是直接忽略校验1~6位地区码的参数，
或是提供另外一个函数。
地区码因为历史遗留或是新增，偶发还是有一些测不准的号，很多场景，有效号检查成无效号的情况还是不能接受的，忽略地区码也是一种做法

**Comment by guanguans** [comment]
> 建议在GetInfo或是IsValid中添加一个忽略校验第5-6位，或是直接忽略校验1-6位地区码的参数， 或是提供另外一个函数。 地区码因为历史遗留或是新增，偶发还是有一些测不准的号，很多场景，有效号检查成无效号的情况还是不能接受的，忽略地区码也是一种做法。 目前我的项目里面为了克服这个问题，手动改源码跳过地区码校验那段了，因为也不是很要求严格的场景

有时间我看一下，或者你这边 `pr` 过来也可以。
